(function(){var h={},mt={},c={id:"607e1d83cfc1309c8742d1678d31f030",dm:["codepku.com","www-codepku-com-afe7.aipage.cn"],js:"tongji.baidu.com/hm-web/js/",etrk:[{id:"%23top-register-action",eventType:"onclick"},{id:"%23course-gift-btn",eventType:"onclick"},{id:"%23formGetCode",eventType:"onclick"},{id:"%23videoModal%3ediv%3ediv%3ediv%5b3%5d%3eform%3ediv%3ebutton",eventType:"onclick"},{id:"%23footerFormGetCode",eventType:"onclick"},{id:"%23modalRegisterPart%3ediv%5b2%5d%3eform%3ediv%3ediv%5b4%5d%3ebutton",eventType:"onclick"},{id:"%23mobileFormGetCode",eventType:"onclick"}],icon:'',ctrk:false,align:-1,nv:1,vdur:1800000,age:31536000000,rec:0,rp:[],trust:1,vcard:9662654,qiao:0,lxb:9662654,kbtrk:0,pt:9662654,aet:'',hca:'CE516BF29FCD0FB9',conv:0,med:0,cvcc:'',cvcf:[],apps:''};var q=void 0,r=!0,t=null,u=!1;mt.cookie={};mt.cookie.set=function(b,a,d){var f;d.$&&(f=new Date,f.setTime(f.getTime()+d.$));document.cookie=b+"="+a+(d.domain?"; domain="+d.domain:"")+(d.path?"; path="+d.path:"")+(f?"; expires="+f.toGMTString():"")+(d.Yb?"; secure":"")};mt.cookie.get=function(b){return(b=RegExp("(^| )"+b+"=([^;]*)(;|$)").exec(document.cookie))?b[2]:t};mt.lang={};mt.lang.e=function(b,a){return"[object "+a+"]"==={}.toString.call(b)};
mt.lang.za=function(b){return mt.lang.e(b,"Number")&&isFinite(b)};mt.lang.ha=function(){return mt.lang.e(c.aet,"String")};mt.lang.i=function(b){return b.replace?b.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):b};mt.lang.trim=function(b){return b.replace(/^\s+|\s+$/g,"")};mt.lang.H=function(b,a){var d=u;if(b==t||!mt.lang.e(b,"Array")||a===q)return d;if(Array.prototype.indexOf)d=-1!==b.indexOf(a);else for(var f=0;f<b.length;f++)if(b[f]===a){d=r;break}return d};
(function(){var b=mt.lang;mt.d={};mt.d.aa=function(a){return document.getElementById(a)};mt.d.ea=function(a,d){var f=[],b=[];if(!a)return b;for(;a.parentNode!=t;){for(var l=0,m=0,p=a.parentNode.childNodes.length,e=0;e<p;e++){var k=a.parentNode.childNodes[e];if(k.nodeName===a.nodeName&&(l++,k===a&&(m=l),0<m&&1<l))break}if((p=""!==a.id)&&d){f.unshift("#"+encodeURIComponent(a.id));break}else p&&(p="#"+encodeURIComponent(a.id),p=0<f.length?p+">"+f.join(">"):p,b.push(p)),f.unshift(encodeURIComponent(String(a.nodeName).toLowerCase())+
(1<l?"["+m+"]":""));a=a.parentNode}b.push(f.join(">"));return b};mt.d.wa=function(a){return(a=mt.d.ea(a,r))&&a.length?String(a[0]):""};mt.d.lb=function(a){return mt.d.ea(a,u)};mt.d.ab=function(a){var b;for(b="A";(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==b)return a;return t};mt.d.cb=function(a){return 9===a.nodeType?a:a.ownerDocument||a.document};mt.d.ib=function(a){var b={top:0,left:0};if(!a)return b;var f=mt.d.cb(a).documentElement;"undefined"!==typeof a.getBoundingClientRect&&(b=a.getBoundingClientRect());
return{top:b.top+(window.pageYOffset||f.scrollTop)-(f.clientTop||0),left:b.left+(window.pageXOffset||f.scrollLeft)-(f.clientLeft||0)}};mt.d.getAttribute=function(a,b){var f=a.getAttribute&&a.getAttribute(b)||t;if(!f&&a.attributes&&a.attributes.length)for(var g=a.attributes,l=g.length,m=0;m<l;m++)g[m].nodeName===b&&(f=g[m].nodeValue);return f};mt.d.N=function(a){var b="document";a.tagName!==q&&(b=a.tagName);return b.toLowerCase()};mt.d.nb=function(a){var d="";a.textContent?d=b.trim(a.textContent):
a.innerText&&(d=b.trim(a.innerText));d&&(d=d.replace(/\s+/g," ").substring(0,255));return d};mt.d.eb=function(a){var b=mt.d.N(a);"input"===b&&("button"===a.type||"submit"===a.type)?a=a.value||"":"img"===b?(b=mt.d.getAttribute,a=b(a,"alt")||b(a,"title")||b(a,"src")):a="body"===b||"html"===b?["(hm-default-content-for-",b,")"].join(""):mt.d.nb(a);return String(a).substring(0,255)};(function(){(mt.d.Ca=function(){function a(){if(!a.P){a.P=r;for(var b=0,f=g.length;b<f;b++)g[b]()}}function b(){try{document.documentElement.doScroll("left")}catch(f){setTimeout(b,
1);return}a()}var f=u,g=[],l;document.addEventListener?l=function(){document.removeEventListener("DOMContentLoaded",l,u);a()}:document.attachEvent&&(l=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",l),a())});(function(){if(!f)if(f=r,"complete"===document.readyState)a.P=r;else if(document.addEventListener)document.addEventListener("DOMContentLoaded",l,u),window.addEventListener("load",a,u);else if(document.attachEvent){document.attachEvent("onreadystatechange",
l);window.attachEvent("onload",a);var g=u;try{g=window.frameElement==t}catch(p){}document.documentElement.doScroll&&g&&b()}})();return function(b){a.P?b():g.push(b)}}()).P=u})();return mt.d})();mt.event={};mt.event.c=function(b,a,d){b.attachEvent?b.attachEvent("on"+a,function(a){d.call(b,a)}):b.addEventListener&&b.addEventListener(a,d,u)};mt.event.preventDefault=function(b){b.preventDefault?b.preventDefault():b.returnValue=u};
(function(){var b=mt.event;mt.g={};mt.g.ga=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.g.yb=/msie (\d+\.\d+)/i.test(navigator.userAgent)?document.documentMode||+RegExp.$1:q;mt.g.cookieEnabled=navigator.cookieEnabled;mt.g.javaEnabled=navigator.javaEnabled();mt.g.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.g.Gb=(window.screen.width||0)+"x"+(window.screen.height||0);mt.g.colorDepth=window.screen.colorDepth||0;mt.g.G=function(){var a;
a=a||document;return parseInt(window.pageYOffset||a.documentElement.scrollTop||a.body&&a.body.scrollTop||0,10)};mt.g.B=function(){var a=document;return parseInt(window.innerHeight||a.documentElement.clientHeight||a.body&&a.body.clientHeight||0,10)};mt.g.orientation=0;(function(){function a(){var a=0;window.orientation!==q&&(a=window.orientation);screen&&(screen.orientation&&screen.orientation.angle!==q)&&(a=screen.orientation.angle);mt.g.orientation=a}a();b.c(window,"orientationchange",a)})();return mt.g})();
mt.o={};mt.o.parse=function(){return(new Function('return (" + source + ")'))()};
mt.o.stringify=function(){function b(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var b=d[a];if(b)return b;b=a.charCodeAt();return"\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)}));return'"'+a+'"'}function a(a){return 10>a?"0"+a:a}var d={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(f){switch(typeof f){case "undefined":return"undefined";case "number":return isFinite(f)?String(f):"null";case "string":return b(f);case "boolean":return String(f);
default:if(f===t)return"null";if(f instanceof Array){var d=["["],l=f.length,m,p,e;for(p=0;p<l;p++)switch(e=f[p],typeof e){case "undefined":case "function":case "unknown":break;default:m&&d.push(","),d.push(mt.o.stringify(e)),m=1}d.push("]");return d.join("")}if(f instanceof Date)return'"'+f.getFullYear()+"-"+a(f.getMonth()+1)+"-"+a(f.getDate())+"T"+a(f.getHours())+":"+a(f.getMinutes())+":"+a(f.getSeconds())+'"';m=["{"];p=mt.o.stringify;for(l in f)if(Object.prototype.hasOwnProperty.call(f,l))switch(e=
f[l],typeof e){case "undefined":case "unknown":case "function":break;default:d&&m.push(","),d=1,m.push(p(l)+":"+p(e))}m.push("}");return m.join("")}}}();mt.localStorage={};mt.localStorage.U=function(){if(!mt.localStorage.k)try{mt.localStorage.k=document.createElement("input"),mt.localStorage.k.type="hidden",mt.localStorage.k.style.display="none",mt.localStorage.k.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.k)}catch(b){return u}return r};
mt.localStorage.set=function(b,a,d){var f=new Date;f.setTime(f.getTime()+d||31536E6);try{window.localStorage?(a=f.getTime()+"|"+a,window.localStorage.setItem(b,a)):mt.localStorage.U()&&(mt.localStorage.k.expires=f.toUTCString(),mt.localStorage.k.load(document.location.hostname),mt.localStorage.k.setAttribute(b,a),mt.localStorage.k.save(document.location.hostname))}catch(g){}};
mt.localStorage.get=function(b){if(window.localStorage){if(b=window.localStorage.getItem(b)){var a=b.indexOf("|"),d=b.substring(0,a)-0;if(d&&d>(new Date).getTime())return b.substring(a+1)}}else if(mt.localStorage.U())try{return mt.localStorage.k.load(document.location.hostname),mt.localStorage.k.getAttribute(b)}catch(f){}return t};
mt.localStorage.remove=function(b){if(window.localStorage)window.localStorage.removeItem(b);else if(mt.localStorage.U())try{mt.localStorage.k.load(document.location.hostname),mt.localStorage.k.removeAttribute(b),mt.localStorage.k.save(document.location.hostname)}catch(a){}};mt.sessionStorage={};mt.sessionStorage.set=function(b,a){if(window.sessionStorage)try{window.sessionStorage.setItem(b,a)}catch(d){}};
mt.sessionStorage.get=function(b){return window.sessionStorage?window.sessionStorage.getItem(b):t};mt.sessionStorage.remove=function(b){window.sessionStorage&&window.sessionStorage.removeItem(b)};mt.Fa={};mt.Fa.log=function(b,a){var d=new Image,f="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[f]=d;d.onload=d.onerror=d.onabort=function(){d.onload=d.onerror=d.onabort=t;d=window[f]=t;a&&a(b)};d.src=b};mt.oa={};
mt.oa.ob=function(){var b="";if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];a&&a.description&&(b=a.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(b=a.GetVariable("$version"))&&(b=b.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(d){}return b};
mt.oa.Vb=function(b,a,d,f,g){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+b+'" width="'+d+'" height="'+f+'"><param name="movie" value="'+a+'" /><param name="flashvars" value="'+(g||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+b+'" width="'+d+'" height="'+f+'" src="'+a+'" flashvars="'+(g||"")+'" allowscriptaccess="always" /></object>'};mt.url={};
mt.url.l=function(b,a){var d=b.match(RegExp("(^|&|\\?|#)("+a+")=([^&#]*)(&|$|#)",""));return d?d[3]:t};mt.url.Wb=function(b){return(b=b.match(/^(https?:)\/\//))?b[1]:t};mt.url.gb=function(b){return(b=b.match(/^(https?:\/\/)?([^\/\?#]*)/))?b[2].replace(/.*@/,""):t};mt.url.da=function(b){return(b=mt.url.gb(b))?b.replace(/:\d+$/,""):b};mt.url.ea=function(b){return(b=b.match(/^(https?:\/\/)?[^\/]*(.*)/))?b[2].replace(/[\?#].*/,"").replace(/^$/,"/"):t};
(function(){function b(){for(var a=u,b=document.getElementsByTagName("script"),f=b.length,f=100<f?100:f,g=0;g<f;g++){var l=b[g].src;if(l&&0===l.indexOf("https://hm.baidu.com/h")){a=r;break}}return a}return h.$a=b})();var x=h.$a;
h.j={xb:"http://tongji.baidu.com/hm-web/welcome/ico",ma:"hm.baidu.com/hm.gif",Na:"tongji.baidu.com",ub:"hmmd",vb:"hmpl",Rb:"utm_medium",tb:"hmkw",Tb:"utm_term",qb:"hmci",Qb:"utm_content",wb:"hmsr",Sb:"utm_source",rb:"hmcu",Pb:"utm_campaign",C:0,r:Math.round(+new Date/1E3),F:Math.round(+new Date/1E3)%65535,protocol:"https:"===document.location.protocol?"https:":"http:",Q:x()||"https:"===document.location.protocol?"https:":"http:",Xb:0,Ta:6E5,Ab:6E5,Hb:5E3,Ua:5,D:1024,Sa:1,A:2147483647,Ga:"hca kb cc cf ci ck cl cm cp cu cw ds vl ep et fl ja ln lo lt rnd si su v cv lv api sn ct u tt hh".split(" "),
I:r,ta:["a","input","button"],Pa:{id:"data-hm-id",X:"data-hm-class",qa:"data-hm-xpath",content:"data-hm-content",T:"data-hm-tag",link:"data-hm-link"},sa:"data-hm-enabled",ra:"data-hm-disabled"};(function(){var b={w:{},c:function(a,b){this.w[a]=this.w[a]||[];this.w[a].push(b)},M:function(a,b){this.w[a]=this.w[a]||[];for(var f=this.w[a].length,g=0;g<f;g++)this.w[a][g](b)}};return h.m=b})();
(function(){function b(b,f){var g=document.createElement("script");g.charset="utf-8";a.e(f,"Function")&&(g.readyState?g.onreadystatechange=function(){if("loaded"===g.readyState||"complete"===g.readyState)g.onreadystatechange=t,f()}:g.onload=function(){f()});g.src=b;var l=document.getElementsByTagName("script")[0];l.parentNode.insertBefore(g,l)}var a=mt.lang;return h.load=b})();
(function(){function b(){var b="";h.a.b.nv?(b=encodeURIComponent(document.referrer),window.sessionStorage?d.set("Hm_from_"+c.id,b):a.set("Hm_from_"+c.id,b,864E5)):b=(window.sessionStorage?d.get("Hm_from_"+c.id):a.get("Hm_from_"+c.id))||"";return b}var a=mt.localStorage,d=mt.sessionStorage;return h.ua=b})();
(function(){var b=h.j,a={init:function(){if(""!==c.icon){var a=c.icon.split("|"),f=b.xb+"?s="+c.id,g="https://hmcdn.baidu.com/static"+a[0]+".gif";document.write("swf"===a[1]||"gif"===a[1]?'<a href="'+f+'" target="_blank"><img border="0" src="'+g+'" width="'+a[2]+'" height="'+a[3]+'"></a>':'<a href="'+f+'" target="_blank">'+a[0]+"</a>")}}};h.m.c("pv-b",a.init);return a})();
(function(){var b=mt.d,a=mt.event,d={Ia:function(){a.c(document,"click",d.L());for(var f=c.etrk.length,g=0;g<f;g++){var l=c.etrk[g],m=decodeURIComponent(String(l.id));-1===m.indexOf(">")&&(0===m.indexOf("#")&&(m=m.substring(1)),(m=b.aa(decodeURIComponent(m)))&&a.c(m,l.eventType,d.Z()))}},Z:function(){return function(a){(a.target||a.srcElement).setAttribute("HM_fix",a.clientX+":"+a.clientY);d.p("#"+encodeURIComponent(this.id),a.type)}},L:function(){return function(a){var g=a.target||a.srcElement;if(g){var l=
g.getAttribute("HM_fix");a=a.clientX+":"+a.clientY;if(l&&l==a)g.removeAttribute("HM_fix");else if(0<c.etrk.length&&(g=b.lb(g))&&g.length)if(l=g.length,a=g[g.length-1],1E4>l*a.split(">").length)for(a=0;a<l;a++)d.Ea(g[a]);else d.Ea(a)}}},Ea:function(a){for(var b={},l=String(a).split(">").length,m=0;m<l;m++)b[a]="",a=a.substring(0,a.lastIndexOf(">"));a=c.etrk.length;for(l=0;l<a;l++)m=decodeURIComponent(String(c.etrk[l].id)),b.hasOwnProperty(m)&&d.p(m)},p:function(a,b){h.a.b.et=1;h.a.b.ep="{id:"+a+",eventType:"+
(b||"click")+"}";h.a.h()}};h.m.c("pv-b",d.Ia);return d})();
(function(){var b=mt.d,a=mt.lang,d=mt.event,f=mt.g,g=h.j,l=h.m,m=[],p={Ha:function(){c.ctrk&&(d.c(document,"mouseup",p.Ra()),d.c(window,"unload",function(){p.R()}),setInterval(function(){p.R()},g.Ta))},Ra:function(){return function(a){a=p.bb(a);if(""!==a){var b=(g.Q+"//"+g.ma+"?"+h.a.Da().replace(/ep=[^&]*/,"ep="+encodeURIComponent(a))).length;b+(g.A+"").length>g.D||(b+encodeURIComponent(m.join("!")+(m.length?"!":"")).length+(g.A+"").length>g.D&&p.R(),m.push(a),(m.length>=g.Ua||/\*a\*/.test(a))&&
p.R())}}},bb:function(k){var d=k.target||k.srcElement;if(0===g.Sa){var n=(d.tagName||"").toLowerCase();if("embed"==n||"object"==n)return""}var s;f.ga?(s=Math.max(document.documentElement.scrollTop,document.body.scrollTop),n=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),n=k.clientX+n,s=k.clientY+s):(n=k.pageX,s=k.pageY);k=p.hb(k,d,n,s);var e=window.innerWidth||document.documentElement.clientWidth||document.body.offsetWidth;switch(c.align){case 1:n-=e/2;break;case 2:n-=e}e=
[];e.push(n);e.push(s);e.push(k.Bb);e.push(k.Cb);e.push(k.Eb);e.push(a.i(k.Db));e.push(k.Ub);e.push(k.pb);(d="a"===(d.tagName||"").toLowerCase()?d:b.ab(d))?(e.push("a"),e.push(a.i(encodeURIComponent(d.href)))):e.push("b");return e.join("*")},hb:function(k,d,n,s){k=b.wa(d);var e=0,g=0,l=0,m=0;if(d&&(e=d.offsetWidth||d.clientWidth,g=d.offsetHeight||d.clientHeight,m=b.ib(d),l=m.left,m=m.top,a.e(d.getBBox,"Function")&&(g=d.getBBox(),e=g.width,g=g.height),"html"===(d.tagName||"").toLowerCase()))e=Math.max(e,
d.clientWidth),g=Math.max(g,d.clientHeight);return{Bb:Math.round(100*((n-l)/e)),Cb:Math.round(100*((s-m)/g)),Eb:f.orientation,Db:k,Ub:e,pb:g}},R:function(){0!==m.length&&(h.a.b.et=2,h.a.b.ep=m.join("!"),h.a.h(),m=[])}},e={La:function(){c.ctrk&&setInterval(e.Ib,g.Hb)},Ib:function(){var a=f.G()+f.B();0<a-h.a.b.vl&&(h.a.b.vl=a)}};l.c("pv-b",p.Ha);l.c("pv-b",e.La);return p})();
(function(){var b=mt.lang,a=mt.d,d=mt.event,f=mt.g,g=h.j,l=h.m,m=+new Date,p=[],e={L:function(){return function(k){if(h.a&&h.a.I&&c.aet&&c.aet.length){var d=k.target||k.srcElement;if(d){var n=h.a.ta,s=a.getAttribute(d,g.sa)!=t?r:u;if(a.getAttribute(d,g.ra)==t)if(s)e.V(e.ca(d,k));else{var f=a.N(d);if(b.H(n,"*")||b.H(n,f))e.V(e.ca(d,k));else for(;d.parentNode!=t;){var s=d.parentNode,f=a.N(s),l="a"===f&&b.H(n,"a")?r:u,f="button"===f&&b.H(n,"button")?r:u,m=a.getAttribute(s,g.sa)!=t?r:u;if(a.getAttribute(s,
g.ra)==t&&(l||f||m)){e.V(e.ca(s,k));break}d=d.parentNode}}}}}},ca:function(k,d){var n={},e=g.Pa;n.id=a.getAttribute(k,e.id)||a.getAttribute(k,"id")||"";n.X=a.getAttribute(k,e.X)||a.getAttribute(k,"class")||"";n.qa=a.getAttribute(k,e.qa)||a.wa(k);n.content=a.getAttribute(k,e.content)||a.eb(k);n.T=a.getAttribute(k,e.T)||a.N(k);n.link=a.getAttribute(k,e.link)||a.getAttribute(k,"href")||"";n.type=d.type||"click";e=b.za(k.offsetTop)?k.offsetTop:0;"click"===d.type?e=f.ga?d.clientY+Math.max(document.documentElement.scrollTop,
document.body.scrollTop):d.pageY:"touchend"===d.type&&(d.ka&&b.e(d.ka.changedTouches,"Array")&&d.ka.changedTouches.length)&&(e=d.ka.changedTouches[0].pageY);n.Ob=e;return n},V:function(a){var d=b.i,d=[+new Date-(h.a.z!==q?h.a.z:m),d(a.id),d(a.X),d(a.T),d(a.qa),d(a.link),d(a.content),a.type,a.Ob].join("*");e.W(d);b.H(["a"],a.T)&&b.e(this.K(),"Function")&&this.K()()},W:function(a){a.length>g.D||(encodeURIComponent(p.join("!")+a).length>g.D&&(e.p(p.join("!")),p=[]),p.push(a))},p:function(a){h.a.b.et=
5;h.a.b.ep=a;h.a.h()},K:function(){return function(){p&&p.length&&(e.p(p.join("!")),p=[])}}};b.ha()&&""!==c.aet&&l.c("pv-b",function(){d.c(document,"click",e.L());"ontouchend"in document&&d.c(window,"touchend",e.L());d.c(window,"unload",e.K())});return e})();
(function(){var b=mt.event,a=mt.g,d=h.j,f=h.m,g=+new Date,l=[],m=t,p={Xa:function(){return function(){h.a&&(h.a.I&&c.aet&&c.aet.length)&&(window.clearTimeout(m),m=window.setTimeout(function(){p.Ka(a.G()+a.B())},150))}},Ka:function(a){p.W([+new Date-(h.a.z!==q?h.a.z:g),a].join("*"))},W:function(a){if(encodeURIComponent(l.join("!")+a).length>d.D||5<l.length)p.p(l.join("!")),l=[];l.push(a)},p:function(b){h.a.b.et=6;h.a.b.vh=a.B();h.a.b.ep=b;h.a.h()},K:function(){return function(){l&&l.length&&(p.p(l.join("!")),
l=[])}}};mt.lang.ha()&&""!==c.aet&&f.c("pv-b",function(){b.c(window,"scroll",p.Xa());b.c(window,"unload",p.K())});return p})();
(function(){var b=mt.d,a=h.j,d=h.load,f=h.ua;h.m.c("pv-b",function(){var g=a.protocol+"//crs.baidu.com/";c.rec&&b.Ca(function(){for(var l=0,m=c.rp.length;l<m;l++){var p=c.rp[l][0],e=c.rp[l][1],k=b.aa("hm_t_"+p);if(e&&!(2==e&&!k||k&&""!==k.innerHTML))k="",k=Math.round(Math.random()*a.A),k=4==e?g+"hl.js?"+["siteId="+c.id,"planId="+p,"rnd="+k].join("&"):g+"t.js?"+["siteId="+c.id,"planId="+p,"from="+f(),"referer="+encodeURIComponent(document.referrer),"title="+encodeURIComponent(document.title),"rnd="+
k].join("&"),d(k)}})})})();(function(){var b=h.j,a=h.load,d=h.ua;h.m.c("pv-b",function(){if(c.trust&&c.vcard){var f="https://tag.baidu.com/vcard/v.js?"+["siteid="+c.vcard,"url="+encodeURIComponent(document.location.href),"source="+d(),"rnd="+Math.round(Math.random()*b.A),"hm=1"].join("&");a(f)}})})();
(function(){function b(){return function(){h.a.b.nv=0;h.a.b.st=4;h.a.b.et=3;h.a.b.ep=h.Y.jb()+","+h.Y.fb();h.a.h()}}function a(){clearTimeout(C);var b;w&&(b="visible"==document[w]);B&&(b=!document[B]);p="undefined"==typeof b?r:b;if((!m||!e)&&p&&k)y=r,n=+new Date;else if(m&&e&&(!p||!k))y=u,s+=+new Date-n;m=p;e=k;C=setTimeout(a,100)}function d(a){var k=document,b="";if(a in k)b=a;else for(var n=["webkit","ms","moz","o"],d=0;d<n.length;d++){var e=n[d]+a.charAt(0).toUpperCase()+a.slice(1);if(e in k){b=
e;break}}return b}function f(b){if(!("focus"==b.type||"blur"==b.type)||!(b.target&&b.target!=window))k="focus"==b.type||"focusin"==b.type?r:u,a()}var g=mt.event,l=h.m,m=r,p=r,e=r,k=r,v=+new Date,n=v,s=0,y=r,w=d("visibilityState"),B=d("hidden"),C;a();(function(){var k=w.replace(/[vV]isibilityState/,"visibilitychange");g.c(document,k,a);g.c(window,"pageshow",a);g.c(window,"pagehide",a);"object"==typeof document.onfocusin?(g.c(document,"focusin",f),g.c(document,"focusout",f)):(g.c(window,"focus",f),
g.c(window,"blur",f))})();h.Y={jb:function(){return+new Date-v},fb:function(){return y?+new Date-n+s:s}};l.c("pv-b",function(){g.c(window,"unload",b())});return h.Y})();
(function(){var b=mt.lang,a=h.j,d=h.load,f={zb:function(f){if((window._dxt===q||b.e(window._dxt,"Array"))&&"undefined"!==typeof h.a){var l=h.a.ba();d([a.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(l)].join(""),f)}},Nb:function(a){if(b.e(a,"String")||b.e(a,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",a])}};return h.Va=f})();
(function(){function b(a,b,n,d){if(!(a===q||b===q||d===q)){if(""===a)return[b,n,d].join("*");a=String(a).split("!");for(var e,f=u,g=0;g<a.length;g++)if(e=a[g].split("*"),String(b)===e[0]){e[1]=n;e[2]=d;a[g]=e.join("*");f=r;break}f||a.push([b,n,d].join("*"));return a.join("!")}}function a(b){for(var e in b)if({}.hasOwnProperty.call(b,e)){var n=b[e];d.e(n,"Object")||d.e(n,"Array")?a(n):b[e]=String(n)}}var d=mt.lang,f=mt.o,g=mt.g,l=h.j,m=h.m,p=h.Va,e={J:[],S:0,Aa:u,s:{pa:"",page:""},init:function(){e.f=
0;m.c("pv-b",function(){e.Wa();e.Ya()});m.c("pv-d",function(){e.Za();e.s.page=""});m.c("stag-b",function(){h.a.b.api=e.f||e.S?e.f+"_"+e.S:"";h.a.b.ct=[decodeURIComponent(h.a.getData("Hm_ct_"+c.id)||""),e.s.pa,e.s.page].join("!")});m.c("stag-d",function(){h.a.b.api=0;e.f=0;e.S=0})},Wa:function(){var a=window._hmt||[];if(!a||d.e(a,"Array"))window._hmt={id:c.id,cmd:{},push:function(){for(var a=window._hmt,b=0;b<arguments.length;b++){var k=arguments[b];d.e(k,"Array")&&(a.cmd[a.id].push(k),"_setAccount"===
k[0]&&(1<k.length&&/^[0-9a-f]{32}$/.test(k[1]))&&(k=k[1],a.id=k,a.cmd[k]=a.cmd[k]||[]))}}},window._hmt.cmd[c.id]=[],window._hmt.push.apply(window._hmt,a)},Ya:function(){var a=window._hmt;if(a&&a.cmd&&a.cmd[c.id])for(var b=a.cmd[c.id],d=/^_track(Event|MobConv|Order|RTEvent)$/,f=0,g=b.length;f<g;f++){var l=b[f];d.test(l[0])?e.J.push(l):e.la(l)}a.cmd[c.id]={push:e.la}},Za:function(){if(0<e.J.length)for(var a=0,b=e.J.length;a<b;a++)e.la(e.J[a]);e.J=t},la:function(a){var b=a[0];if(e.hasOwnProperty(b)&&
d.e(e[b],"Function"))e[b](a)},_setAccount:function(a){1<a.length&&/^[0-9a-f]{32}$/.test(a[1])&&(e.f|=1)},_setAutoPageview:function(a){if(1<a.length&&(a=a[1],u===a||r===a))e.f|=2,h.a.xa=a},_trackPageview:function(a){if(1<a.length&&a[1].charAt&&"/"===a[1].charAt(0)){e.f|=4;h.a.b.et=0;h.a.b.ep="";h.a.b.vl=g.G()+g.B();h.a.b.kb=0;h.a.fa?(h.a.b.nv=0,h.a.b.st=4):h.a.fa=r;var b=h.a.b.u,d=h.a.b.su;h.a.b.u=l.protocol+"//"+document.location.host+a[1];e.Aa||(h.a.b.su=document.location.href);h.a.h();h.a.b.u=b;
h.a.b.su=d;h.a.z=+new Date}},_trackEvent:function(a){2<a.length&&(e.f|=8,h.a.b.nv=0,h.a.b.st=4,h.a.b.et=4,h.a.b.ep=d.i(a[1])+"*"+d.i(a[2])+(a[3]?"*"+d.i(a[3]):"")+(a[4]?"*"+d.i(a[4]):""),h.a.h())},_setCustomVar:function(a){if(!(4>a.length)){var b=a[1],n=a[4]||3;if(0<b&&6>b&&0<n&&4>n){e.S++;for(var f=(h.a.b.cv||"*").split("!"),g=f.length;g<b-1;g++)f.push("*");f[b-1]=n+"*"+d.i(a[2])+"*"+d.i(a[3]);h.a.b.cv=f.join("!");a=h.a.b.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,"");""!==a?h.a.setData("Hm_cv_"+
c.id,encodeURIComponent(a),c.age):h.a.Fb("Hm_cv_"+c.id)}}},_setUserTag:function(a){if(!(3>a.length)){var e=d.i(a[1]);a=d.i(a[2]);if(e!==q&&a!==q){var n=decodeURIComponent(h.a.getData("Hm_ct_"+c.id)||""),n=b(n,e,1,a);h.a.setData("Hm_ct_"+c.id,encodeURIComponent(n),c.age)}}},_setVisitTag:function(a){if(!(3>a.length)){var f=d.i(a[1]);a=d.i(a[2]);if(f!==q&&a!==q){var n=e.s.pa,n=b(n,f,2,a);e.s.pa=n}}},_setPageTag:function(a){if(!(3>a.length)){var f=d.i(a[1]);a=d.i(a[2]);if(f!==q&&a!==q){var n=e.s.page,
n=b(n,f,3,a);e.s.page=n}}},_setReferrerOverride:function(a){1<a.length&&(h.a.b.su=a[1].charAt&&"/"===a[1].charAt(0)?l.protocol+"//"+window.location.host+a[1]:a[1],e.Aa=r)},_trackOrder:function(b){b=b[1];d.e(b,"Object")&&(a(b),e.f|=16,h.a.b.nv=0,h.a.b.st=4,h.a.b.et=94,h.a.b.ep=f.stringify(b),h.a.h())},_trackMobConv:function(a){if(a={webim:1,tel:2,map:3,sms:4,callback:5,share:6}[a[1]])e.f|=32,h.a.b.et=93,h.a.b.ep=a,h.a.h()},_trackRTPageview:function(b){b=b[1];d.e(b,"Object")&&(a(b),b=f.stringify(b),
512>=encodeURIComponent(b).length&&(e.f|=64,h.a.b.rt=b))},_trackRTEvent:function(b){b=b[1];if(d.e(b,"Object")){a(b);b=encodeURIComponent(f.stringify(b));var g=function(a){var b=h.a.b.rt;e.f|=128;h.a.b.et=90;h.a.b.rt=a;h.a.h();h.a.b.rt=b},n=b.length;if(900>=n)g.call(this,b);else for(var n=Math.ceil(n/900),s="block|"+Math.round(Math.random()*l.A).toString(16)+"|"+n+"|",m=[],w=0;w<n;w++)m.push(w),m.push(b.substring(900*w,900*w+900)),g.call(this,s+m.join("|")),m=[]}},_setUserId:function(a){a=a[1];p.zb();
p.Nb(a)},_setAutoTracking:function(a){if(1<a.length&&(a=a[1],u===a||r===a))h.a.ya=a},_setAutoEventTracking:function(a){if(1<a.length&&(a=a[1],u===a||r===a))h.a.I=a}};e.init();h.Oa=e;return h.Oa})();
(function(){function b(){"undefined"===typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=r,this.b={},this.ya=this.xa=r,this.I=k.I,this.ta=g.ha()&&0<c.aet.length?c.aet.split(","):"",this.fa=u,this.init())}var a=mt.url,d=mt.Fa,f=mt.oa,g=mt.lang,l=mt.cookie,m=mt.g,p=mt.localStorage,e=mt.sessionStorage,k=h.j,v=h.m;b.prototype={ia:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length===a.length},Ba:function(a,b){a=a.replace(/^https?:\/\//,
"");return 0===a.indexOf(b)},O:function(b){for(var d=0;d<c.dm.length;d++)if(-1<c.dm[d].indexOf("/")){if(this.Ba(b,c.dm[d]))return r}else{var e=a.da(b);if(e&&this.ia(e,c.dm[d]))return r}return u},ba:function(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(this.ia(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[\/\?#].*/,"");return a},va:function(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&this.Ba(document.location.href,d))return d.replace(/^[^\/]+(\/.*)/,
"$1")+"/"}return"/"},mb:function(){if(!document.referrer)return k.r-k.C>c.vdur?1:4;var b=u;this.O(document.referrer)&&this.O(document.location.href)?b=r:(b=a.da(document.referrer),b=this.ia(b||"",document.location.hostname));return b?k.r-k.C>c.vdur?1:4:3},getData:function(a){try{return l.get(a)||e.get(a)||p.get(a)}catch(b){}},setData:function(a,b,d){try{l.set(a,b,{domain:this.ba(),path:this.va(),$:d}),d?p.set(a,b,d):e.set(a,b)}catch(f){}},Fb:function(a){try{l.set(a,"",{domain:this.ba(),path:this.va(),
$:-1}),e.remove(a),p.remove(a)}catch(b){}},Lb:function(){var a,b,d,e,f;k.C=this.getData("Hm_lpvt_"+c.id)||0;13===k.C.length&&(k.C=Math.round(k.C/1E3));b=this.mb();a=4!==b?1:0;if(d=this.getData("Hm_lvt_"+c.id)){e=d.split(",");for(f=e.length-1;0<=f;f--)13===e[f].length&&(e[f]=""+Math.round(e[f]/1E3));for(;2592E3<k.r-e[0];)e.shift();f=4>e.length?2:3;for(1===a&&e.push(k.r);4<e.length;)e.shift();d=e.join(",");e=e[e.length-1]}else d=k.r,e="",f=1;this.setData("Hm_lvt_"+c.id,d,c.age);this.setData("Hm_lpvt_"+
c.id,k.r);d=k.r===this.getData("Hm_lpvt_"+c.id)?"1":"0";if(0===c.nv&&this.O(document.location.href)&&(""===document.referrer||this.O(document.referrer)))a=0,b=4;this.b.nv=a;this.b.st=b;this.b.cc=d;this.b.lt=e;this.b.lv=f},Da:function(){for(var a=[],b=this.b.et,d=+new Date,e=0,f=k.Ga.length;e<f;e++){var g=k.Ga[e],l=this.b[g];"undefined"!==typeof l&&""!==l&&("tt"!==g||"tt"===g&&0===b)&&(("ct"!==g||"ct"===g&&0===b)&&("kb"!==g||"kb"===g&&3===b))&&a.push(g+"="+encodeURIComponent(l))}switch(b){case 0:a.push("sn="+
k.F);this.b.rt&&a.push("rt="+encodeURIComponent(this.b.rt));break;case 3:a.push("sn="+k.F);break;case 5:a.push("sn="+k.F);a.push("_lpt="+this.z);a.push("_ct="+d);break;case 6:a.push("sn="+k.F);a.push("_lpt="+this.z);a.push("_ct="+d);break;case 85:a.push("sn="+k.F);break;case 90:this.b.rt&&a.push("rt="+this.b.rt)}return a.join("&")},Mb:function(){this.Lb();this.b.si=c.id;this.b.hca="0"===c.hca?q:c.hca;this.b.su=document.referrer;this.b.hh=window.location.hash;this.b.ds=m.Gb;this.b.cl=m.colorDepth+
"-bit";this.b.ln=String(m.language).toLowerCase();this.b.ja=m.javaEnabled?1:0;this.b.ck=m.cookieEnabled?1:0;this.b.lo="number"===typeof _bdhm_top?1:0;this.b.fl=f.ob();this.b.v="1.2.39";this.b.cv=decodeURIComponent(this.getData("Hm_cv_"+c.id)||"");this.b.tt=document.title||"";this.b.vl=m.G()+m.B();var b=document.location.href;this.b.cm=a.l(b,k.ub)||"";this.b.cp=a.l(b,k.vb)||a.l(b,k.Rb)||"";this.b.cw=a.l(b,k.tb)||a.l(b,k.Tb)||"";this.b.ci=a.l(b,k.qb)||a.l(b,k.Qb)||"";this.b.cf=a.l(b,k.wb)||a.l(b,k.Sb)||
"";this.b.cu=a.l(b,k.rb)||a.l(b,k.Pb)||""},init:function(){try{this.Mb(),0===this.b.nv?this.Kb():this.na(".*"),h.a=this,this.Qa(),v.M("pv-b"),this.Jb()}catch(a){var b=[];b.push("si="+c.id);b.push("n="+encodeURIComponent(a.name));b.push("m="+encodeURIComponent(a.message));b.push("r="+encodeURIComponent(document.referrer));d.log(k.Q+"//"+k.ma+"?"+b.join("&"))}},Jb:function(){function a(){v.M("pv-d")}this.xa?(this.fa=r,this.b.et=0,this.b.ep="",this.b.vl=m.G()+m.B(),this.h(a)):a();this.z=+new Date},h:function(a){if(this.ya){var b=
this;b.b.rnd=Math.round(Math.random()*k.A);v.M("stag-b");var e=k.Q+"//"+k.ma+"?"+b.Da();v.M("stag-d");b.Ma(e);d.log(e,function(d){b.na(d);g.e(a,"Function")&&a.call(b)})}},Qa:function(){var b=document.location.hash.substring(1),d=RegExp(c.id),e=a.da(document.referrer)===k.Na?1:0,f=a.l(b,"jn"),g=/^heatlink$|^select$|^pageclick$/.test(f);b&&(d.test(b)&&e&&g)&&(this.b.rnd=Math.round(Math.random()*k.A),b=document.createElement("script"),b.setAttribute("type","text/javascript"),b.setAttribute("charset",
"utf-8"),b.setAttribute("src",k.protocol+"//"+c.js+f+".js?"+this.b.rnd),f=document.getElementsByTagName("script")[0],f.parentNode.insertBefore(b,f))},Ma:function(a){var b=e.get("Hm_unsent_"+c.id)||"",d=this.b.u?"":"&u="+encodeURIComponent(document.location.href),b=encodeURIComponent(a.replace(/^https?:\/\//,"")+d)+(b?","+b:"");e.set("Hm_unsent_"+c.id,b)},na:function(a){var b=e.get("Hm_unsent_"+c.id)||"";b&&(a=encodeURIComponent(a.replace(/^https?:\/\//,"")),a=RegExp(a.replace(/([\*\(\)])/g,"\\$1")+
"(%26u%3D[^,]*)?,?","g"),(b=b.replace(a,"").replace(/,$/,""))?e.set("Hm_unsent_"+c.id,b):e.remove("Hm_unsent_"+c.id))},Kb:function(){var a=this,b=e.get("Hm_unsent_"+c.id);if(b)for(var b=b.split(","),f=function(b){d.log(k.Q+"//"+decodeURIComponent(b),function(b){a.na(b)})},g=0,l=b.length;g<l;g++)f(b[g])}};return new b})();var z=h.j,A=h.load;if(c.apps){var D=[z.protocol,"//ers.baidu.com/app/s.js?"];D.push(c.apps);A(D.join(""))}
(function(){var b=mt.event,a=mt.lang,d=h.j;if(c.kbtrk&&"undefined"!==typeof h.a){h.a.b.kb=a.za(h.a.b.kb)?h.a.b.kb:0;var f=function(){h.a.b.et=85;h.a.b.ep=h.a.b.kb;h.a.h()};b.c(document,"keyup",function(){h.a.b.kb++});b.c(window,"unload",function(){f()});setInterval(f,d.Ab)}})();var E=h.j,F=h.load;c.pt&&F([E.protocol,"//ada.baidu.com/phone-tracker/insert_bdtj?sid=",c.pt].join(""));var G=h.j,H=h.load;c.lxb&&H([G.protocol,"//lxbjs.baidu.com/lxb.js?sid=",c.lxb].join(""));var I=h.load,J=h.j.protocol;
if(c.qiao){for(var K=[J+"//goutong.baidu.com/site/"],L=c.id,M=5381,N=L.length,O=0;O<N;O++)M=(33*M+Number(L.charCodeAt(O)))%4294967296;2147483648<M&&(M-=2147483648);K.push(M%1E3+"/");K.push(c.id+"/b.js");K.push("?siteId="+c.qiao);I(K.join(""))}
(function(){var b=mt.g,a=mt.lang,d=mt.event,f=mt.o;if("undefined"!==typeof h.a&&(c.med||(!b.ga||7<b.yb)&&c.cvcc)){var g,l,m,p,e=function(a){if(a.item){for(var b=a.length,d=Array(b);b--;)d[b]=a[b];return d}return[].slice.call(a)},k=function(a,b){for(var d in a)if(a.hasOwnProperty(d)&&b.call(a,d,a[d])===u)return u},v=function(b,d){var e={};e.n=g;e.t="clk";e.v=b;if(d){var k=d.getAttribute("href"),l=d.getAttribute("onclick")?""+d.getAttribute("onclick"):t,n=d.getAttribute("id")||"";m.test(k)?(e.sn="mediate",
e.snv=k):a.e(l,"String")&&m.test(l)&&(e.sn="wrap",e.snv=l);e.id=n}h.a.b.et=86;h.a.b.ep=f.stringify(e);h.a.h();for(e=+new Date;400>=+new Date-e;);};if(c.med)l="/zoosnet",g="swt",m=/swt|zixun|call|chat|zoos|business|talk|kefu|openkf|online|\/LR\/Chatpre\.aspx/i,p={click:function(){for(var a=[],b=e(document.getElementsByTagName("a")),b=[].concat.apply(b,e(document.getElementsByTagName("area"))),b=[].concat.apply(b,e(document.getElementsByTagName("img"))),d,f,g=0,k=b.length;g<k;g++)d=b[g],f=d.getAttribute("onclick"),
d=d.getAttribute("href"),(m.test(f)||m.test(d))&&a.push(b[g]);return a}};else if(c.cvcc){l="/other-comm";g="other";m=c.cvcc.q||q;var n=c.cvcc.id||q;p={click:function(){for(var a=[],b=e(document.getElementsByTagName("a")),b=[].concat.apply(b,e(document.getElementsByTagName("area"))),b=[].concat.apply(b,e(document.getElementsByTagName("img"))),d,f,g,k=0,l=b.length;k<l;k++)d=b[k],m!==q?(f=d.getAttribute("onclick"),g=d.getAttribute("href"),n?(d=d.getAttribute("id"),(m.test(f)||m.test(g)||n.test(d))&&
a.push(b[k])):(m.test(f)||m.test(g))&&a.push(b[k])):n!==q&&(d=d.getAttribute("id"),n.test(d)&&a.push(b[k]));return a}}}if("undefined"!==typeof p&&"undefined"!==typeof m){var s;l+=/\/$/.test(l)?"":"/";var y=function(b,d){if(s===d)return v(l+b,d),u;if(a.e(d,"Array")||a.e(d,"NodeList"))for(var e=0,f=d.length;e<f;e++)if(s===d[e])return v(l+b+"/"+(e+1),d[e]),u};d.c(document,"mousedown",function(b){b=b||window.event;s=b.target||b.srcElement;var d={};for(k(p,function(b,e){d[b]=a.e(e,"Function")?e():document.getElementById(e)});s&&
s!==document&&k(d,y)!==u;)s=s.parentNode})}}})();(function(){var b=mt.d,a=mt.lang,d=mt.event,f=mt.o;if("undefined"!==typeof h.a&&a.e(c.cvcf,"Array")&&0<c.cvcf.length){var g={Ja:function(){for(var a=c.cvcf.length,f,p=0;p<a;p++)(f=b.aa(decodeURIComponent(c.cvcf[p])))&&d.c(f,"click",g.Z())},Z:function(){return function(){h.a.b.et=86;var a={n:"form",t:"clk"};a.id=this.id;h.a.b.ep=f.stringify(a);h.a.h()}}};b.Ca(function(){g.Ja()})}})();
(function(){var b=mt.event,a=mt.o;if(c.med&&"undefined"!==typeof h.a){var d=+new Date,f={n:"anti",sb:0,kb:0,clk:0},g=function(){h.a.b.et=86;h.a.b.ep=a.stringify(f);h.a.h()};b.c(document,"click",function(){f.clk++});b.c(document,"keyup",function(){f.kb=1});b.c(window,"scroll",function(){f.sb++});b.c(window,"unload",function(){f.t=+new Date-d;g()});b.c(window,"load",function(){setTimeout(g,5E3)})}})();})();
